from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

def generate_pdf_report(output_path, patient_summary, trial_title, match_score, summary):
    """
    Generates a professional PDF report for a single clinical trial match.
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(Paragraph("NeuroMatch Lite - Clinical Trial Report", styles['Title']))
    story.append(Spacer(1, 20))

    # Patient Summary Section
    story.append(Paragraph("<b>Patient Diagnosis Summary:</b>", styles['Heading2']))
    story.append(Paragraph(patient_summary, styles['Normal']))
    story.append(Spacer(1, 15))

    # Trial Details Section
    story.append(Paragraph(f"<b>Trial Match: {trial_title}</b>", styles['Heading2']))
    
    # Match Score Table
    score_data = [["Analysis Factor", "Result"],
                  ["Overall Match Score", f"{int(match_score * 100)}%"]]
    
    t = Table(score_data, colWidths=[200, 100])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#2D3748")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    story.append(t)
    story.append(Spacer(1, 15))

    # Summary Section
    story.append(Paragraph("<b>Clinical Rationale:</b>", styles['Heading3']))
    story.append(Paragraph(summary, styles['Normal']))
    story.append(Spacer(1, 20))

    # Next Steps
    story.append(Paragraph("<b>Recommended Next Steps:</b>", styles['Heading3']))
    steps = [
        "1. Present this report to your treating neurologist.",
        "2. Review the inclusion/exclusion criteria in detail.",
        "3. Contact the study coordinator listed on ClinicalTrials.gov.",
        "4. Do not make any changes to your medication without medical supervision."
    ]
    for step in steps:
        story.append(Paragraph(f"• {step}", styles['Normal']))
    
    story.append(Spacer(1, 40))
    story.append(Paragraph("<i>Disclaimer: This report is generated by AI and is intended for informational purposes only. It does not constitute medical advice.</i>", styles['Normal']))

    doc.build(story)
    return output_path
